# Generated by Django 5.0.6 on 2025-09-23 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie_name', models.CharField(max_length=200)),
                ('pais_mais_comum', models.CharField(max_length=200)),
                ('data_descobrimento', models.DateTimeField(verbose_name='data descobrimento')),
                ('letal', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Acidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_acidentado', models.CharField(max_length=200)),
                ('pais_de_ocorrencia', models.CharField(max_length=200)),
                ('data_ocorrencia', models.DateTimeField(verbose_name='data ocorrência')),
                ('sobreviveu', models.BooleanField()),
                ('especie_que_mordeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dadosapp.especie')),
            ],
        ),
    ]
