# Generated by Django 5.0.6 on 2025-09-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dadosapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especie',
            old_name='especie_name',
            new_name='especie_nome',
        ),
    ]
