# Generated by Django 5.2.6 on 2025-09-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadosapp', '0002_rename_especie_name_especie_especie_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='acidente',
            name='latitude',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acidente',
            name='longitude',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
